### ISSUE TITLE
Typescript: missing props & methods on CastRayCollectorJS

### ISSUE THREAD

**Issue by DennisSmolek** [jrouwe/JoltPhysics.js#141] opened 2024-04-02 16:10 UTC
In the Ray Cast Example, 
You start with the more complex collision collector which has you specify different event handling functions. 
In the `OnBody` function [you place the body value on the collector](https://github.com/jrouwe/JoltPhysics.js/blob/aa742fda357053bafdf807a043e573009f8833aa/Examples/ray_cast.html#L65)

However, `body` is not a valid property.

I figured this was just an example/javascript hack where the body value can be specified on the class and passed to the later results.

However, a few lines later it calls: `collector.UpdateEarlyOutFraction()` which actually doesn't exist on the type at all. The`CastRayCollectorJS` version also doesn't seem to be an extension so any of the other methods on `CastRayCollector` are getting flagged.

Current Type.d.ts values:
```js
class CastRayCollector {
        Reset(): void;
        SetContext(inContext: TransformedShape): void;
        GetContext(): TransformedShape;
        UpdateEarlyOutFraction(inFraction: number): void;
        ResetEarlyOutFraction(inFraction?: number): void;
        ForceEarlyOut(): void;
        ShouldEarlyOut(): boolean;
        GetEarlyOutFraction(): number;
        GetPositiveEarlyOutFraction(): number;
    }
    class CastRayCollectorJS {
        constructor();
        Reset(): void;
        OnBody(inBody: Body): void;
        AddHit(inResult: RayCastResult): void;
    }
```

**Comment by jrouwe** [comment] 2024-04-02 19:16
> However, body is not a valid property.

Correct, I'm just using the collector to temporarily store a property. I could have used any variable.

> However, a few lines later it calls: collector.UpdateEarlyOutFraction() which actually doesn't exist on the type at all.

This is essentially a duplicate of #138, `JoltJS.idl` declares this as:

```
interface CastRayCollector {
	// ...
	void UpdateEarlyOutFraction(float inFraction);
	// ...
};

[JSImplementation="CastRayCollector"]
interface CastRayCollectorJS {
	// ...
};
```

Which means `CastRayCollectorJS` should extend `CastRayCollector` (just like `VehicleConstraintCallbacksJS` should extend `VehicleConstraintCallbacksEm`). When that is fixed, you'll get the `UpdateEarlyOutFaction` function.

**Closed** 2024-04-05 09:23 UTC
